[pack_meta]
title = "SnorshCraft"
author = "byteford"
version = "1.3.2"
override_dir = "overrides"

[minecraft]
version = "1.12.2"
forge_version = "14.23.0.2491"

[[mods]]
name = "Actually Additions"
author = "Ellpeck"
project_id = 228404
file_id = 2485639

[[mods]]
name = "Akashic Tome"
author = "Vazkii"
project_id = 250577
file_id = 2476494

[[mods]]
name = "AntiGhost"
author = "Thorgeig"
project_id = 273279
file_id = 2458392

[[mods]]
name = "AppleSkin"
author = "squeek502"
project_id = 248787
file_id = 2476721

[[mods]]
name = "Applied Energistics 2"
author = "AlgorithmX2"
project_id = 223794
file_id = 2486738

[[mods]]
name = "Aroma1997Core"
author = "Aroma1997"
project_id = 223735
file_id = 2486142

[[mods]]
name = "Aroma1997s Dimensional World"
author = "Aroma1997"
project_id = 60092
file_id = 2440965

[[mods]]
name = "Astral Sorcery"
author = "HellFirePvP"
project_id = 241721
file_id = 2452200

[[mods]]
name = "AutoRegLib"
author = "Vazkii"
project_id = 250363
file_id = 2445828

[[mods]]
name = "Baby Animals Model Swapper"
author = "MrIbby"
project_id = 227979
file_id = 2437287

[[mods]]
name = "Bad Wither No Cookie - Reloaded"
author = "kreezxil"
project_id = 261251
file_id = 2464169

[[mods]]
name = "Baubles"
author = "azanor"
project_id = 227083
file_id = 2459083

[[mods]]
name = "Bed Bugs"
author = "gr8pefish"
project_id = 254508
file_id = 2443328

[[mods]]
name = "Better Builder's Wands"
author = "Portablejim"
project_id = 238403
file_id = 2443194

[[mods]]
name = "Better Than Weagles"
author = "DarkMorford"
project_id = 273532
file_id = 2486279

[[mods]]
name = "BetterFps"
author = "Guichaguri"
project_id = 229876
file_id = 2469845

[[mods]]
name = "BiblioCraft"
author = "JDSinclair"
project_id = 228027
file_id = 2456043

[[mods]]
name = "Bookshelf"
author = "darkh4x"
project_id = 228525
file_id = 2481208

[[mods]]
name = "Botania"
author = "Vazkii"
project_id = 225643
file_id = 2486296

[[mods]]
name = "Chameleon"
author = "jaquadro"
project_id = 230497
file_id = 2450900

[[mods]]
name = "Chameleon Creepers"
author = "Velocity666"
project_id = 242617
file_id = 2435079

[[mods]]
name = "Chest Cow"
author = "jf908"
project_id = 264897
file_id = 2434541

[[mods]]
name = "Chest Transporter"
author = "CubeX2"
project_id = 78778
file_id = 2460961

[[mods]]
name = "Chisel"
author = "tterrag1098"
project_id = 235279
file_id = 2479333

[[mods]]
name = "Chisels & Bits"
author = "AlgorithmX2"
project_id = 231095
file_id = 2483470

[[mods]]
name = "CodeChicken Lib 1.8.+"
author = "covers1624"
project_id = 242818
file_id = 2485334

[[mods]]
name = "CoFH Core"
author = "TeamCoFH"
project_id = 69162
file_id = 2469614

[[mods]]
name = "CoFH World"
author = "TeamCoFH"
project_id = 271384
file_id = 2463404

[[mods]]
name = "Common Capabilities"
author = "kroeser"
project_id = 247007
file_id = 2467504

[[mods]]
name = "ConnectedTexturesMod"
author = "tterrag1098"
project_id = 267602
file_id = 2485010

[[mods]]
name = "Controlling"
author = "jaredlll08"
project_id = 250398
file_id = 2482216

[[mods]]
name = "Cooking for Blockheads"
author = "BlayTheNinth"
project_id = 231484
file_id = 2464472

[[mods]]
name = "CraftTweaker"
author = "jaredlll08"
project_id = 239197
file_id = 2462468

[[mods]]
name = "Creeper Confetti"
author = "SR261097"
project_id = 222548
file_id = 2443326

[[mods]]
name = "Creeperade"
author = "elias54"
project_id = 250559
file_id = 2442525

[[mods]]
name = "Cucumber"
author = "BlakeBr0"
project_id = 272335
file_id = 2475975

[[mods]]
name = "Custom Main Menu"
author = "lumien231"
project_id = 226406
file_id = 2476121

[[mods]]
name = "Cyclops Core"
author = "kroeser"
project_id = 232758
file_id = 2483504

[[mods]]
name = "Dark Utilities"
author = "darkh4x"
project_id = 242195
file_id = 2477761

[[mods]]
name = "Deep Resonance"
author = "McJty"
project_id = 233398
file_id = 2450473

[[mods]]
name = "Diet Hoppers"
author = "RWTema"
project_id = 278385
file_id = 2482543

[[mods]]
name = "Doggy Talents"
author = "Percivalalb"
project_id = 271050
file_id = 2484373

[[mods]]
name = "Dynamic Surroundings"
author = "OreCruncher"
project_id = 238891
file_id = 2482521

[[mods]]
name = "ElecCore | Rendering Library"
author = "Elec332"
project_id = 227391
file_id = 2467767

[[mods]]
name = "Embers"
author = "elucent"
project_id = 251918
file_id = 2448903

[[mods]]
name = "Ender Storage 1.8.+"
author = "covers1624"
project_id = 245174
file_id = 2468431

[[mods]]
name = "Environmental Tech"
author = "ValkyrieofNight"
project_id = 245453
file_id = 2484590

[[mods]]
name = "EvilCraft"
author = "kroeser"
project_id = 74610
file_id = 2483512

[[mods]]
name = "Exchangers"
author = "Jacky1356400"
project_id = 270183
file_id = 2466211

[[mods]]
name = "Extra Utilities"
author = "RWTema"
project_id = 225561
file_id = 2481036

[[mods]]
name = "Flux Networks"
author = "Ollie_Lansdell"
project_id = 248020
file_id = 2481720

[[mods]]
name = "Food Expansion"
author = "Lellson"
project_id = 235328
file_id = 2457523

[[mods]]
name = "FTB Utilities"
author = "FTB"
project_id = 237102
file_id = 2485624

[[mods]]
name = "FTBLib"
author = "FTB"
project_id = 237167
file_id = 2485622

[[mods]]
name = "Global XP - Share XP levels with your friends"
author = "bl4ckscor3"
project_id = 268647
file_id = 2462695

[[mods]]
name = "GPS Mod / Stalker mod"
author = "Aroma1997"
project_id = 247855
file_id = 2470263

[[mods]]
name = "Grue"
author = "Shinoow"
project_id = 235133
file_id = 2450761

[[mods]]
name = "IKWID (I Know What I'm Doing)"
author = "InsomniaKitten"
project_id = 271492
file_id = 2469710

[[mods]]
name = "Immersive Engineering"
author = "BluSunrize"
project_id = 231951
file_id = 2479843

[[mods]]
name = "Immersive Petroleum"
author = "theFlaxbeard"
project_id = 268250
file_id = 2460649

[[mods]]
name = "Integrated Dynamics"
author = "kroeser"
project_id = 236307
file_id = 2483520

[[mods]]
name = "Integrated Tunnels"
author = "kroeser"
project_id = 251389
file_id = 2474021

[[mods]]
name = "Inventory Tweaks"
author = "Kobata"
project_id = 223094
file_id = 2463769

[[mods]]
name = "Iron Chests"
author = "progwml6"
project_id = 228756
file_id = 2442829

[[mods]]
name = "IvToolkit"
author = "Ivorforce"
project_id = 224535
file_id = 2443253

[[mods]]
name = "JourneyMap"
author = "techbrew"
project_id = 32274
file_id = 2482291

[[mods]]
name = "Just a Few Fish"
author = "Tmtravlr"
project_id = 235261
file_id = 2448283

[[mods]]
name = "Just Another Snad"
author = "DarkMorford"
project_id = 276722
file_id = 2475874

[[mods]]
name = "Just Enough Items (JEI)"
author = "mezz"
project_id = 238222
file_id = 2486866

[[mods]]
name = "Just Enough Resources (JER)"
author = "Way2muchnoise"
project_id = 240630
file_id = 2463648

[[mods]]
name = "KleeSlabs"
author = "BlayTheNinth"
project_id = 241895
file_id = 2443462

[[mods]]
name = "Lost Souls"
author = "McJty"
project_id = 271998
file_id = 2465796

[[mods]]
name = "Mantle"
author = "mDiyo"
project_id = 74924
file_id = 2474052

[[mods]]
name = "McJtyLib"
author = "McJty"
project_id = 233105
file_id = 2451959

[[mods]]
name = "Mod Name Tooltip"
author = "mezz"
project_id = 238747
file_id = 2463742

[[mods]]
name = "ModTweaker"
author = "jaredlll08"
project_id = 220954
file_id = 2455995

[[mods]]
name = "More Overlays"
author = "feldim2425"
project_id = 243478
file_id = 2434979

[[mods]]
name = "Morph-o-Tool"
author = "Vazkii"
project_id = 245287
file_id = 2475117

[[mods]]
name = "Mouse Tweaks"
author = "YaLTeR97"
project_id = 60089
file_id = 2462627

[[mods]]
name = "MTLib"
author = "jaredlll08"
project_id = 253211
file_id = 2453543

[[mods]]
name = "Mystical Agriculture"
author = "BlakeBr0"
project_id = 246640
file_id = 2481507

[[mods]]
name = "Nature's Compass"
author = "ChaosTheDude"
project_id = 252848
file_id = 2455634

[[mods]]
name = "NoNausea"
author = "lumien231"
project_id = 226035
file_id = 2432422

[[mods]]
name = "Open Glider"
author = "gr8pefish"
project_id = 252354
file_id = 2464501

[[mods]]
name = "OpenBlocks Elevator"
author = "VsnGamer"
project_id = 250832
file_id = 2442766

[[mods]]
name = "Psi"
author = "Vazkii"
project_id = 241665
file_id = 2480499

[[mods]]
name = "Quark"
author = "Vazkii"
project_id = 243121
file_id = 2480530

[[mods]]
name = "Ranged Pumps"
author = "raoulvdberge"
project_id = 247496
file_id = 2441326

[[mods]]
name = "Reborn Core"
author = "modmuss50"
project_id = 237903
file_id = 2486707

[[mods]]
name = "Reborn Storage"
author = "modmuss50"
project_id = 256662
file_id = 2458387

[[mods]]
name = "Recurrent Complex"
author = "Ivorforce"
project_id = 223150
file_id = 2482140

[[mods]]
name = "Redstone Arsenal"
author = "TeamCoFH"
project_id = 70631
file_id = 2469625

[[mods]]
name = "Redstone Flux"
author = "TeamCoFH"
project_id = 270789
file_id = 2448933

[[mods]]
name = "Refined Storage"
author = "raoulvdberge"
project_id = 243076
file_id = 2477560

[[mods]]
name = "Resource Loader"
author = "lumien231"
project_id = 226447
file_id = 2477566

[[mods]]
name = "RFTools"
author = "McJty"
project_id = 224641
file_id = 2465110

[[mods]]
name = "RFTools Dimensions"
author = "McJty"
project_id = 240950
file_id = 2478237

[[mods]]
name = "Roots"
author = "elucent"
project_id = 246183
file_id = 2481157

[[mods]]
name = "Rustic"
author = "thatguy3039"
project_id = 256141
file_id = 2479117

[[mods]]
name = "SimpleHarvest"
author = "TehNut"
project_id = 240783
file_id = 2475234

[[mods]]
name = "Simply Enchanting"
author = "Dyonovan"
project_id = 269948
file_id = 2445128

[[mods]]
name = "Sonar Core"
author = "Ollie_Lansdell"
project_id = 239418
file_id = 2481716

[[mods]]
name = "Steve's Carts Reborn"
author = "modmuss50"
project_id = 253462
file_id = 2485220

[[mods]]
name = "Storage Drawers"
author = "jaquadro"
project_id = 223852
file_id = 2484308

[[mods]]
name = "Stupid Things"
author = "Furgl"
project_id = 267901
file_id = 2483683

[[mods]]
name = "SubLib"
author = "senpaisubaraki"
project_id = 251678
file_id = 2454127

[[mods]]
name = "The Lost Cities"
author = "McJty"
project_id = 269024
file_id = 2484717

[[mods]]
name = "The One Probe"
author = "McJty"
project_id = 245211
file_id = 2469334

[[mods]]
name = "TheBOMPlugin"
author = "osum4est"
project_id = 273404
file_id = 2462865

[[mods]]
name = "Thermal Cultivation"
author = "TeamCoFH"
project_id = 271835
file_id = 2469623

[[mods]]
name = "Thermal Dynamics"
author = "TeamCoFH"
project_id = 227443
file_id = 2469621

[[mods]]
name = "Thermal Expansion"
author = "TeamCoFH"
project_id = 69163
file_id = 2469736

[[mods]]
name = "Thermal Foundation"
author = "TeamCoFH"
project_id = 222880
file_id = 2469615

[[mods]]
name = "Tinkers Construct"
author = "mDiyo"
project_id = 74072
file_id = 2476509

[[mods]]
name = "Tomb Many Graves 2"
author = "M4thG33k"
project_id = 262823
file_id = 2469850

[[mods]]
name = "TOP Addons"
author = "DrManganese"
project_id = 247111
file_id = 2486162

[[mods]]
name = "TorchMaster"
author = "xalcon"
project_id = 254268
file_id = 2462030

[[mods]]
name = "Traverse"
author = "ProfessorProspector"
project_id = 267769
file_id = 2478137

[[mods]]
name = "Tree Growing Simulator"
author = "tterrag1098"
project_id = 246764
file_id = 2452234

[[mods]]
name = "ValkyrieLib"
author = "ValkyrieofNight"
project_id = 245480
file_id = 2484877

[[mods]]
name = "Waystones"
author = "BlayTheNinth"
project_id = 245755
file_id = 2464463

[[mods]]
name = "Wearable Backpacks"
author = "koppeh"
project_id = 257572
file_id = 2453047

[[mods]]
name = "XL Food Mod"
author = "mariot789"
project_id = 247217
file_id = 2467580

[[mods]]
name = "XNet"
author = "McJty"
project_id = 260912
file_id = 2464091

[[mods]]
name = "ZeroCore"
author = "ZeroNoRyouki"
project_id = 247921
file_id = 2442435
